"""init DB named ai for  customers

Revision ID: 28a2ab98fb2b
Revises: 68eac1439578
Create Date: 2025-08-21 03:27:20.881190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a2ab98fb2b'
down_revision = '68eac1439578'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kis_customers',
    sa.Column('id_user', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('rcve_odyr', sa.Integer(), nullable=False),
    sa.Column('acnt_evlu_amt', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_kis_customers_id_user'), 'kis_customers', ['id_user'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_kis_customers_id_user'), table_name='kis_customers', schema='ai')
    op.drop_table('kis_customers', schema='ai')
    # ### end Alembic commands ###
