"""type change almt_pymt_prca

Revision ID: 2be305e2d46c
Revises: 321a5e03e9b3
Create Date: 2025-09-01 15:38:10.269670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be305e2d46c'
down_revision = '321a5e03e9b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
