"""recreate kis_dc_contract with sst_join_dt

Revision ID: 321a5e03e9b3
Revises: fab4ebc8a730
Create Date: 2025-09-01 15:34:03.072164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321a5e03e9b3'
down_revision = 'fab4ebc8a730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kis_dc_contract',
    sa.Column('ctrt_no', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('odtp_name', sa.String(), nullable=False, comment='근무처명: On Duty Place Name'),
    sa.Column('etco_dt', sa.String(length=8), nullable=False, comment='입사일자: Entering a Company Date'),
    sa.Column('midl_excc_dt', sa.String(length=8), nullable=False, comment='중간정산일자: Middle Exact Calculation Date'),
    sa.Column('sst_join_dt', sa.String(length=8), nullable=False, comment='제도가입일자: System join Date'),
    sa.Column('almt_pymt_prca', sa.String(length=8), nullable=False, comment='부담금납입원금: Allotment Payment Principal'),
    sa.Column('utlz_pfls_amt', sa.BigInteger(), nullable=False, comment='운용손익금액: Utilization Profitloss Amount'),
    sa.Column('evlu_acca_smtl_amt', sa.BigInteger(), nullable=False, comment='평가적립금합계금액: Evaluation Accumulated Fund Sum'),
    sa.PrimaryKeyConstraint('ctrt_no'),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kis_dc_contract', schema='ai')
    # ### end Alembic commands ###
