"""add columns for customers

Revision ID: 87f9a7af1e4d
Revises: 33260cc4c76c
Create Date: 2025-08-23 05:18:17.607172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f9a7af1e4d'
down_revision = '33260cc4c76c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kis_customers',
    sa.Column('id_user', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('acnt_type', sa.String(), nullable=False, comment='계좌유형: Account Type'),
    sa.Column('prd_type_cd', sa.Integer(), nullable=False, comment='상품코드: product type code'),
    sa.Column('acnt_bgn_dt', sa.String(length=8), nullable=False, comment='계좌 개설 일시: Account Begin Date (YYYYMMDD)'),
    sa.Column('acnt_evlu_amt', sa.BigInteger(), nullable=False, comment='계좌 평가액: Account Evaluation Amount'),
    sa.Column('rcve_odyr', sa.Integer(), nullable=False, comment='수령연차: Receive Order of Year'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_kis_customers_id_user'), 'kis_customers', ['id_user'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_kis_customers_id_user'), table_name='kis_customers', schema='ai')
    op.drop_table('kis_customers', schema='ai')
    # ### end Alembic commands ###
