"""id_users -> customer_id

Revision ID: a08964b58ea1
Revises: 1540d1645410
Create Date: 2025-08-23 05:36:57.135705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08964b58ea1'
down_revision = '1540d1645410'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kis_accounts',
    sa.Column('account_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('acnt_type', sa.String(), nullable=False, comment='계좌유형: Account Type'),
    sa.Column('prd_type_cd', sa.Integer(), nullable=False, comment='상품코드: product type code'),
    sa.Column('acnt_bgn_dt', sa.String(length=8), nullable=False, comment='계좌 개설 일시: Account Begin Date (YYYYMMDD)'),
    sa.Column('acnt_evlu_amt', sa.BigInteger(), nullable=False, comment='계좌 평가액: Account Evaluation Amount'),
    sa.Column('rcve_odyr', sa.Integer(), nullable=False, comment='수령연차: Receive Order of Year'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_kis_accounts_account_id'), 'kis_accounts', ['account_id'], unique=False, schema='ai')
    op.create_index(op.f('ix_ai_kis_accounts_customer_id'), 'kis_accounts', ['customer_id'], unique=False, schema='ai')
    op.create_table('kis_customers',
    sa.Column('customer_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('brth_dt', sa.String(length=8), nullable=False, comment='생년월일: Birth Date (YYYYMMDD)'),
    sa.Column('age_band', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_kis_customers_customer_id'), 'kis_customers', ['customer_id'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_kis_customers_customer_id'), table_name='kis_customers', schema='ai')
    op.drop_table('kis_customers', schema='ai')
    op.drop_index(op.f('ix_ai_kis_accounts_customer_id'), table_name='kis_accounts', schema='ai')
    op.drop_index(op.f('ix_ai_kis_accounts_account_id'), table_name='kis_accounts', schema='ai')
    op.drop_table('kis_accounts', schema='ai')
    # ### end Alembic commands ###
