"""sst_join_dt & sync pk flags for kis_accounts

Revision ID: fab4ebc8a730
Revises: 952df2effef2
Create Date: 2025-09-01 15:20:56.897375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab4ebc8a730'
down_revision = '952df2effef2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
